services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports: ['9092:9092']

  jobmanager:
    image: flink:1.20-scala_2.12
    command: jobmanager
    ports: ['8081:8081']
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    hostname: jobmanager

  taskmanager:
    image: flink:1.20-scala_2.12
    command: taskmanager
    depends_on: [jobmanager]
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager;taskmanager.numberOfTaskSlots: 4"
    hostname: taskmanager

  dynamo:
    image: amazon/dynamodb-local:2.4.0
    ports: ['8000:8000']

networks:
  default:
    name: flink-network
